require.config({
     urlArgs:"rnd="+(new Date()).getTime(),
    paths:{
        'jquery':'../../lib/jquery/jquery.min',
        'bootstrap':'../../lib/bootstrap/dist/js/bootstrap.min',
		'moment':'../../lib/moment/min/moment.min',
		'NVis':'../../lib/hicharts/NVis.min',
		'utils':'./Compatibility/utils',
		
		
		'tabs':'./components/tabs',
		'bread':'./components/bread',
		'alert':'./components/alert',
		'confirm':'./components/confirm',
		'prompt':'./components/prompt',
		'drop':'./components/drop',
		'search':'./components/search',
		'gallery':'./components/gallery',
		'progressbar':'./components/progressbar',
		'drop2':'./components/drop2',
		'drop3':'./components/drop3',
		'treable':'./components/treable',
		'treable2':'./components/treable2',
		'sutable':'./components/sutable',
		'timerange':'./components/timerange',
		'blend':'./components/blend',
		'vList':'./components/vList',
		'vList3':'./components/vList3',
		'bubble':'./components/bubble',
		'bootdrop':'./components/bootDrop',
		'datepicker':'./components/daterangepicker',
        'field':'./components/field'
    },
    shim:{
		bootstrap:{
			deps:['jquery']
		},
		drop:{
			deps:['jquery']
		},
		drop2:{
			deps:['bootstrap']
		},
		alert:{
			deps:['bootstrap']
		},
		confirm:{
			deps:['bootstrap']
		},
		prompt:{
			deps:['bootstrap']
		},
		gallery:{
			deps:['bootstrap']
		},
		treable:{
			deps:['bootstrap','tabs','drop2']
		},
		treable2:{
			deps:['bootstrap','tabs','drop2']
		},		
		sutable:{
			deps:['bootstrap']
		},
		bubble:{
			deps:['bootstrap']
		},
		timerange:{
			deps:['drop']
		},
		vList3:{
			deps:['search']
		},
		blend:{
			deps:['vList3','bread','drop3']
		},
		NVis:{
			deps:['jquery']
		},
		'com/ndpmedia/vis/ChartWidget':{
			deps:['NVis']
		},
		'com/ndpmedia/vis/ChartEventListener':{
			deps:['NVis']
		},
		bootdrop:{
			deps:['bootstrap']
		},
		datepicker:{
			deps:['moment']
		}
    }
});
