require(['./config'],function(){
    require(['jquery','utils'],function($){
        require(['bootstrap','./components/drop'],function(){
            $("div.ndp-drop-wrapper[name=inline-drop]").drop({
                data:[1,2,3,4,5,6]
            });
            $("div.ndp-drop-wrapper[name=split-drop]").drop({
                type:2,
                data:[1,2,3]
            });
            $("div.ndp-drop-wrapper[name=inline-drop2]").drop({
                data:[1,2,3,4,5,6,7,8]
            }); 
            $("div.ndp-drop-wrapper[name=split-drop2]").drop({
                type:2,
                data:[1,2,3]
            }); 
            $("div.ndp-drop-wrapper[name=tree-drop2]").drop({
                data:[{text:"新疆"},
					  {text:"陕西",sub:[{text:"西安"},
									  {text:"咸阳"}]},
					  {text:"四川",sub:[{text:"成都"},
									  {text:"宜宾"}]},
					  {text:"浙江",sub:[{name:"杭州",
									   sub:[{name:"西溪"},
											{name:"武林"}]}]},
					  {text:"湖北"},
					  {text:"湖南"}],
				caret:"glyphicon-menu-right"
            }).on("drop_item_click",function(e){
				alert(11111);
			});  
            $("div.ndp-drop-wrapper[name=group-drop2]").drop({
				type:3,
                data:[
					  {name:"中国区",group:[{text:"四川省"},
									  {text:"河北省"}]},
					  {name:"东亚区",group:[{text:"日本"},
									  {text:"韩国"}]},
					  {name:"美洲区",group:[{name:"加拿大"},
									     {name:"美国"},
									     {name:"阿根廷"}]}],
				caret:"glyphicon-menu-right"
            });
			
            $("div.ndp-drop-wrapper[name=disable-drop2]").drop({
                data:[{name:"中国",disable:true},{name:"美国"},"德国","加拿大","澳大利亚"]
            }); 
            $("div.ndp-drop-wrapper[name=line-drop2]").drop({
                data:["中国",{name:"美国"},{name:"德国",split:true},
					  "加拿大","澳大利亚","法国","爱尔兰","以色列"]
            }); 
            $("div.ndp-drop-wrapper[name=checkbox-drop2]").drop({
				type:4,
                data:["中国","加拿大","澳大利亚","法国"]
            }); 			
        });
    });
});