require(['./config'],function(){
    require(['jquery','utils'],function($){
        require(['bootstrap','./components/sutable'],function(){
			$(".ndp-sutable-wrapper").sutable({
				head:["状态",'名称',"妆化率","出价","产出率","库存","定位","历史","美工","现实"],
				body:[{label:[true,"1-1","1","2","3","4"],
					   sub:[{label:[true,"1-2","1","2","3","4"]},
							{label:[true,"1-3","1","2","3","4"]},
							{label:[true,"1-4","1","2","3","4"],
							 sub:[
								{label:[true,"1-1-1","1-1","2-1","3-1","4"]},
								 {label:[true,"1-1-2","1-2","2-2","3-1","4"]}
								]
							},
						   ]
					  },{label:[true,"2-1","1","2","3","4"],
					   sub:[{label:[true,"2-2","1","2","3","4"]},
							{label:[true,"2-3","1","2","3","4"]},
							{label:[true,"2-4","1","2","3","4"],
							 sub:[
								{label:[true,"1-1-1","1-1","2-1","3-1","4"]},
								 {label:[true,"1-1-2","1-2","2-2","3-1","4"]}
								]
							},
						   ]
					  },{label:[true,"3-1","1","2","3","4"],
					   sub:[{label:[true,"3-2","1","2","3","4"]},
							{label:[true,"3-3","1","2","3","4"]},
							{label:[true,"3-4","1","2","3","4"],
							}
						   ]
					  },
					  
				]
			});
        });
    });
});